use_frameworks!

platform :ios, '11.0'

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'
  pod 'LZIOSCommon', :git=> 'git@github.com:rookielz93/LZIOSCommon.git'

  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end
